#!/usr/bin/env python3.3

import argparse
import http.client
import sys

# Read commandline arguments
parser = argparse.ArgumentParser(description='TODO: Make usage friendlier')
parser.add_argument('--host')
parser.add_argument('--port')
args = parser.parse_args()



if not (args.host and args.port):
        sys.stderr.write("Usage: --host=<host> and --port=<port>\n")
        sys.exit(1)


# Post data for broadcast
data = sys.stdin.read()
h = http.client.HTTPConnection('%s:%s' % (args.host, args.port))
h.request("POST","/qplan", data, {"Content-type": "application/text"})
